export interface Env {
  BUILDINGS_KV: KVNamespace;
  AUTH_STORE: DurableObjectNamespace;
  AUTH_STORE_RATE_LIMITER: RateLimit;
  AUTH_CLIENT_RATE_LIMITER: RateLimit;
  AUTH_CHALLENGE_CREATE_RATE_LIMITER: RateLimit;
  AUTH_SENSITIVE_RATE_LIMITER: RateLimit;
  PUBLIC_API_RATE_LIMITER: RateLimit;
  VPC_SERVICE: Fetcher;
  MINECRAFT_SERVER_URL: string;
  MINECRAFT_SERVER_ADDRESS: string;
  MINECRAFT_SERVER_PORT: string;
  CLOUDFLARE_ACCESS_ISSUER: string;
  CLOUDFLARE_ACCESS_AUD: string;
  MIKWEB_AUTH_CLIENT_SECRET?: string;
  WEBAUTHN_RP_ID?: string;
  WEBAUTHN_ORIGIN?: string;
}
